### PR TITLE
V1.4.1

### PR DESCRIPTION
**Pull request by francisco-dlp**
New patch release. It includes #22.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
@conda-forge-admin, please rerender

**Comment by ericpre** [comment]
Testing in python 3.7 seems to be unhappy...  maybe it would be more simple to ignore the compiler and python 3.7 migration for now? There are still a few dependencies which are not ready.

**Comment by francisco-dlp** [comment]
It seems that Py37 is happy after fixing a few things in https://github.com/hyperspy/hyperspy/pull/2072

**Comment by francisco-dlp** [comment]
appveyor is not happy, and it seems that we can't do anything about it other than waiting for the next conda release, see https://github.com/conda-forge/pycroscopy-feedstock/pull/4#issuecomment-427567650.

I suggest releasing nevertheless and:

* Rerun the windows build once the new version of conda is released
* Add a release note explaining that anaconda windows users should upgrade using pip in the meantime.

**Comment by ericpre** [comment]
Surprisingly, conda install pillow 5.2, while 5.3 is availalbe. Is it worth trying to pin pillow to 5.3, just in case?!
I have tried to install hyperspy 1.4 with 
```
conda install -c conda-forge hyperspy
```
and I get the same error as on appveyor, while with
```
conda install -c conda-forge hyperspy pillow=5.3
```
the tests run fine.
Other than that, comparing the log of the last [hyperspy release](https://ci.appveyor.com/project/conda-forge/hyperspy-feedstock/build/1.0.121/job/l5nk6xd45ak3494g?fullLog=true) with [this one](https://ci.appveyor.com/project/conda-forge/hyperspy-feedstock/builds/19658171/job/rvf0530uel4g6v6k?fullLog=true) doesn't show not much differences in terms of dependency...

**Comment by francisco-dlp** [comment]
Nice idea, the on-going build is testing it.

**Comment by ericpre** [comment]
Great, it seems that this workaround works for this time! :smiley:

**Comment by ericpre** [comment]
Following https://github.com/hyperspy/hyperspy/pull/1750, we can remove lxml from the run requirements.

**Comment by francisco-dlp** [comment]
Done, thanks!

**Pull request merged**
