### PR TITLE
Make two outputs: hyperspy-base and hyperspy.

### PR DESCRIPTION
**Pull request by ericpre**
Attempt to make several outputs to install guis and development tools:
- `hyperspy-base` is the `hyperspy` pypi package
- `hyperspy` is a meta-package: it installs `hyperspy-base` + guis
- `hyperspy-dev` is a meta-package: it installs `hyperspy` + the development tools (cython, pytest, libraries to build the doc, etc.)

It re-introduces the installation of GUIs (similarly to #26) and it should allow:
```
conda install hyperspy-base --only-deps -c conda-forge
```
as mentioned in https://github.com/hyperspy/hyperspy/issues/1950#issuecomment-390385929.

### CODE REVIEW

**Comment by ericpre** [comment]
This PR makes the recipe a metapackage similarly to what have been done with:
- https://github.com/conda-forge/matplotlib-feedstock/pull/178
- https://github.com/AnacondaRecipes/numpy-feedstock/blob/master/recipe/meta.yaml

The GUIs dependency failure is the same as in #26 and the reason may be that the hyperspy-gui-* package are missing the build with the new compilers. One way to solve it is to make them noarch.

**Comment by ericpre** [comment]
The failures are caused by an issue with the EELSDB, which seems to be down. There were a couple of red-herring issues at the beginning but I think that it is all fine.

Regarding the name, I basically followed the numpy and matplotlib example with the idea that installing the package `hyperspy` should provide what most people expect (hyperspy + GUIs + pyqt).

**Comment by francisco-dlp** [comment]
EELSdb seems to be fine now.

**Comment by ericpre** [comment]
> EELSdb seems to be fine now.

Yes, @llajaunie fixed it! :smiley: 

Now, we may have another intermittent issue.

**Comment by ericpre** [comment]
@msarahan and @soapy1, could the [appveyor failure of the last commit](https://ci.appveyor.com/project/conda-forge/hyperspy-feedstock/builds/20623827) be related to the anaconda server changes mentioned on gitter?

```
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 415, in execute
    verify=args.verify)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2215, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1971, in test
    is_conda=metadata.name() == 'conda')
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 852, in create_env
    execute_actions(actions, index, verbose=config.debug)
  File "C:\Miniconda36-x64\lib\site-packages\conda\common\io.py", line 46, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 390, in execute_actions
    execute_instructions(plan, index, verbose)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 600, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda36-x64\lib\site-packages\conda\instructions.py", line 64, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\package_cache_data.py", line 605, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/noarch/nbconvert-5.4.0-0.tar.bz2>
Elapsed: 00:00.144480
CF-RAY: 480eae906c80c53e-ORD
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

I have already restart the appveyor build once, which means that the same error occurs 4 times in the last hour.

**Comment by ericpre** [comment]
Similar issue with travis.

**Comment by ericpre** [comment]
There is nothing special with `nbconvert` in this recipe. Until two hours ago (in this [build](https://ci.appveyor.com/project/conda-forge/hyperspy-feedstock/builds/20620247)), it was picking up
```
     nbconvert:               5.3.1-py_1                conda-forge
```
as expected.

**Comment by ericpre** [comment]
travis with new compilers:
```
     nbconvert:          5.4.0-1                                conda-forge/label/gcc7
```
travis with old compilers
```
    nbconvert:            5.4.0-0                              conda-forge

```

**Comment by ericpre** [comment]
@francisco-dlp can you try to restart the two circleCI builds which are failing?

**Comment by francisco-dlp** [comment]
They're running now.

**Comment by ericpre** [comment]
Thanks, all green now!

**Pull request merged**
