### PR TITLE
Release 1.6.2

### PR DESCRIPTION
**Pull request by francisco-dlp**

### CODE REVIEW

**Comment by ericpre** [comment]
I have a branch which adds python 3.9 but there are conflicts with this branch. Shall I make a new PR?

**Comment by ericpre** [comment]
This is the branch: https://github.com/ericpre/hyperspy-feedstock/tree/1.6.2

**Comment by francisco-dlp** [comment]
Closing this one then.

**Comment by ericpre** [comment]
https://github.com/conda-forge/hyperspy-feedstock/pull/52

**Pull request closed without merging**
