### PR TITLE
Release v1.3.2

### PR DESCRIPTION
**Pull request by francisco-dlp**

### CODE REVIEW

**Comment by isuruf** [comment]
Can this recipe be noarch? https://conda-forge.org/docs/meta.html#building-noarch-packages

**Comment by francisco-dlp** [comment]
I don't think so since it is not a pure python package, it contains some Cython code, or am I wrong?

**Comment by isuruf** [comment]
Then you should add compilers.
```
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
```

**Comment by francisco-dlp** [comment]
Done, thanks @isuruf

**Comment by isuruf** [comment]
Add a license_file entry to about section.
Change home url from from https to http. (https link doesn't work)

Is the cython extension C or C++?

**Comment by francisco-dlp** [comment]
After committing the changes that you suggested circleci is not happy. Do you think that the issue is related to 4dab0756116d27e12be76683b1f20ee648938e18?

**Comment by francisco-dlp** [comment]
The Cython extension is C. It used to work fine as it was.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by francisco-dlp** [comment]
License file added.

**Pull request merged**
